FROM mitmproxy/mitmproxy

WORKDIR /home/mitmproxy

COPY ./mitmproxy /home/mitmproxy

CMD ["mitmdump", "-s", "/home/mitmproxy/proxy.py", "--mode", "transparent", "--listen-host", "0.0.0.0", "--listen-port", "8080"]
